# Generated by Django 6.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='order number')),
                ('order_type', models.CharField(choices=[('DELIVERY', 'Delivery'), ('TAKEOUT', 'Takeout'), ('DINE_IN', 'Dine In')], max_length=20, verbose_name='order type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tax')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='delivery fee')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('delivery_address', models.JSONField(blank=True, null=True, verbose_name='delivery address')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='delivery instructions')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery time')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('special_instructions', models.TextField(blank=True, verbose_name='special instructions')),
                ('modifiers', models.JSONField(default=list, verbose_name='modifiers')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'order_items',
            },
        ),
    ]
