# Generated by Django 6.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_orders', models.IntegerField(default=0, verbose_name='total orders')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total revenue')),
                ('total_customers', models.IntegerField(default=0, verbose_name='total customers')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='average order value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'daily sales report',
                'verbose_name_plural': 'daily sales reports',
                'db_table': 'daily_sales_reports',
                'ordering': ['-date'],
            },
        ),
    ]
