# Generated by Django 6.0.2 on 2026-02-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesreport',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='restaurants.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysalesreport',
            unique_together={('restaurant', 'date')},
        ),
    ]
