# Generated by Django 5.1.14 on 2026-02-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_reserva_d35c68_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_restaur_f79f12_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_user_id_d4fda7_idx',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(verbose_name='guest count'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='reservation number'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=50, verbose_name='table number'),
        ),
        migrations.AlterModelTable(
            name='table',
            table='restaurant_tables',
        ),
    ]
