# Generated by Django 6.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('category', models.CharField(max_length=100, verbose_name='category')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current quantity')),
                ('unit', models.CharField(choices=[('KG', 'Kilograms'), ('G', 'Grams'), ('L', 'Liters'), ('ML', 'Milliliters'), ('PCS', 'Pieces')], max_length=10, verbose_name='unit')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minimum quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'inventory item',
                'verbose_name_plural': 'inventory items',
                'db_table': 'inventory_items',
            },
        ),
    ]
