# Generated by Django 5.1.14 on 2026-02-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('BILLING', 'Billing'), ('ACCOUNT', 'Account'), ('ORDER', 'Order'), ('RESERVATION', 'Reservation')], default='GENERAL', max_length=20, verbose_name='category'),
        ),
    ]
