# Generated by Django 6.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('rate_limit', models.IntegerField(default=1000, verbose_name='rate limit (requests/hour)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='webhook URL')),
                ('events', models.JSONField(default=list, verbose_name='subscribed events')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('secret', models.CharField(max_length=100, verbose_name='secret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'db_table': 'webhooks',
            },
        ),
    ]
