# Generated by Django 6.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'menu category',
                'verbose_name_plural': 'menu categories',
                'db_table': 'menu_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/', verbose_name='image')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='calories')),
                ('allergens', models.JSONField(default=list, verbose_name='allergens')),
                ('dietary_tags', models.JSONField(default=list, verbose_name='dietary tags')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('preparation_time', models.IntegerField(default=15, verbose_name='preparation time (minutes)')),
                ('order_count', models.IntegerField(default=0, verbose_name='order count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'db_table': 'menu_items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
